### ISSUE TITLE
"Hide from recent task list" option

### ISSUE THREAD

**Issue by za006** [breezy-weather/breezy-weather#408]
### Describe your idea

Hide rencent tasklist button is useful 
Because all closed  if rencent list close at android 8

Thanks

For one alreay have this function app
![Screenshot_20230822_190943](https://github.com/breezy-weather/breezy-weather/assets/134183191/57925e9d-9efa-487e-a9ff-1d67bde8a599)
![Screenshot_20230822_190937](https://github.com/breezy-weather/breezy-weather/assets/134183191/9f58dcfc-bde0-4bde-a787-22f9fd70d8ad)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open or closed issue.
- [X] I have written a short but informative title.
- [X] My idea is not related to an existing feature described in the [Homepage](https://github.com/breezy-weather/breezy-weather/blob/main/docs/HOMEPAGE.md) document.
- [X] I have updated the app to **[version 4.6.3 or later](https://github.com/breezy-weather/breezy-weather/releases/latest)**.

**Comment by papjul** [comment]
If the app is used, it should show in recents.

Please:
1) Give more details about how it works exactly
2) Describe your use case

**Comment by za006** [comment]
What i want function show
https://youtube.com/shorts/KH8ylRlNO6c?feature=share

**Comment by papjul** [comment]
OK, that's what I thought.

What about the use case? Why would you need something like that?

**Comment by za006** [comment]
because 
a old phone system at android 8 or 9 .. recent takelist kill  is end the whole app  (don't know where problem) .  and can't wake up by pusher message
b a clean habit .this tool app use to open once .at  rain_day  always often look over .then kill at recentlist every time  use

**Comment by papjul** [comment]
No, Android doesn't kill apps removed from recent list. If it does, that's a bug or a non-standard behavior implemented by your manufacturer.

Have a look at https://dontkillmyapp.com/ to find ways to circumvent this behavior.

If it still doesn't work after following steps:
- If it's a custom ROM, report the bug to the maintainer, or change ROM
- If it's the standard ROM, contact your manufacturer support

We don't plan to add workarounds for bugs inside custom Android versions.
